# ???? ??
spring.application.name=SmartSub-Backend

# H2 DB ??
spring.datasource.url=jdbc:h2:~/smartsubdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console ?? (???)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Spring Batch ??
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# ??? CSV ?? ??
product.csv.path=classpath:product_test.csv
