# ? Spring App Name
spring.application.name=SmartSub-Backend

# ? MySQL DB ??
spring.datasource.url=jdbc:mysql://localhost:3306/smartsub?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=smartsub
spring.datasource.password=smartpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? Spring Batch ??
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# ? CSV ?? (Spring Batch?? ?? ? ??)
product.csv.path=classpath:product_test.csv

# ? Slack Webhook ??
spring.config.import=optional:classpath:application-secret.properties
